edit_main_contents
itomaTech/freemarket_sample_49a pull request #17
Opened 2019-04-28 12:29 UTC by yusuke39

2019-04-28 12:31 UTC, yusuke39 commented
#what
TOPページのメイン画面
#why
商品の一覧表示

2019-04-30 03:12 UTC, yusuke39 commented
https://gyazo.com/e632a764f82a66755e9c9deb5c65dd5e

2019-04-30 03:16 UTC, ghost requested changes
全体的に修正をお願い致します。

2019-04-30 03:16 UTC, hiroki5123 commented on Gemfile
> +gem 'jquery-rails'
最後に空行入れましょう

2019-04-30 03:16 UTC, hiroki5123 commented on app/assets/javascripts/slick.js
> +  });
インデント合わせましょう

2019-04-30 03:16 UTC, hiroki5123 commented on app/assets/stylesheets/content.scss
> +        div{
この指定方法はよくないので、何かクラスを作ってそこにスタイルを適用させてください

2019-04-30 03:16 UTC, hiroki5123 commented on app/views/products/_content.html.haml
> +      %a{href: '#'}
link_toで仮置きしましょう

2019-04-30 03:16 UTC, hiroki5123 commented on app/views/products/_content.html.haml
> +        =image_tag 'mer.jpeg', size: '1900×600'
大きさはCSS側に

2019-04-30 03:16 UTC, hiroki5123 commented on app/views/products/_content.html.haml
> +      %a{href: '#'}
こちらも

2019-04-30 03:16 UTC, hiroki5123 commented on app/views/products/_header.html.haml
> +          = image_tag 'mercari_logo_horizontal.png', size: '150x50', alt: 'mercari', class: 'input-dfault'
こちらも

2019-04-30 03:16 UTC, hiroki5123 commented on app/views/products/_header.html.haml
> +            %ul.main-gnav__right__user__menu__box{data: {id: 'main-header__user-items'}}
ここにulあるのおかしい気がするのですが、ここにulを入れているのは何故ですか？

2019-04-30 03:16 UTC, hiroki5123 commented on app/views/products/_header.html.haml
> +                  =image_tag 'face-icon.png', size: '32', alt: 'face-icon'
こちらも

2019-04-30 06:02 UTC, yusuke39 commented
コメントありがとうございます！
修正しました。
（ul置いている意味なかったです、、、気づきませんでした。ありがとうございます）

2019-04-30 06:03 UTC, yusuke39 commented
コメントありがとうございます！
修正しました。
（ul置いている意味なかったです、、、気づきませんでした。ありがとうございます）

2019-04-30 06:13 UTC, miyagit commented on app/views/layouts/application.html.haml
>      %link{:href => "https://use.fontawesome.com/releases/v5.6.1/css/all.css", :rel => "stylesheet"}/
ハッシュロケットをやめましょう。

2019-04-30 06:13 UTC, miyagit commented on app/assets/stylesheets/content.scss
> +        &__lang{
インデント修正しましょう。

2019-04-30 06:30 UTC, yusuke39 commented
コメントありがとうございます
修正しました！

2019-04-30 06:42 UTC, hiroki5123 commented
Sider落ちてるのはいいんでしょうか？

2019-04-30 06:44 UTC, ghost requested changes

2019-04-30 06:44 UTC, hiroki5123 commented on app/views/products/_products.html.haml
> +    %a{href: 'https://item.mercari.com/jp/m27278690533/'}
こちらもlink_toで

2019-04-30 06:44 UTC, hiroki5123 commented on app/views/products/_products.html.haml
> +        =image_tag 'https://static.mercdn.net/thumb/photos/m27278690533_1.jpg?1555391521', {data: {src: 'https://item.mercari.com/jp/m27278690533/'}}
ここでdata指定してるのってなんでですか？

2019-04-30 06:44 UTC, hiroki5123 commented on app/views/products/_header.html.haml
> +          %li{data: {id: 'main-header__user-gnav', key: 'todo', url: '#'}}
現時点でdataって使ってないなら削除してもいいと思うのですが、今後使う予定ってあるんですか？

2019-04-30 07:27 UTC, yusuke39 commented
修正しました

2019-04-30 07:52 UTC, hiroki5123 commented
こちらは指摘した箇所を削除してくださいと言っているわけではなくて、質問としてなぜこのように実装したのかの理由を聞いていますので、質問に答えていただきますようお願い致します。

こちらとしても何故そのような実装をしたのかが見ただけではわからない場合は質問をさせていただいており、開発の背景やそれらがなぜ必要になったかの理由を知りたいだけなのですが。。。

2019-04-30 07:57 UTC, yusuke39 commented
コメントありがとうございます
質問の件回答させて頂きます。
カスタムデーター に関しては、わからない部分が出てきた時、本物のメルカリを確認した際に
カスタムデーターを利用していたので、後で使うことがあるかと思い実装してしまっておりました！
お手数おかけしてしまい申し訳ございません。

2019-04-30 08:06 UTC, ghost approved these changes
返信ありがとうございます。
基本的にあとで使うことがあるものは、あとのプルリクエストで実装してください。
プルリクエストは今回必要なもののみを入れるよう、お願い致します。

2019-04-30 08:09 UTC, yusuke39 commented
ご返信ありがとうございます。
今後は必要になった際に実装するように、注意していきます！
今回はトップページを整えたかったので、カスタムデーターは一旦外しておきます。

2019-04-30 08:14 UTC, miyagit reviewed
すべてのファイルに言えることですが、基本的に=のあとはスペースを一つつけるようにすると見やすいのでそうしましょう！！

2019-04-30 08:23 UTC, yusuke39 commented
コメントありがとうございます！
修正しました
ご確認お願い致します。

2019-04-30 08:26 UTC, miyagit commented on app/assets/stylesheets/index.scss
>                position: relative;
ここがすごいインデントずれてますね。

2019-04-30 08:26 UTC, miyagit commented on app/assets/stylesheets/index.scss
> +                .face-icon{
ここもそうですね。

2019-04-30 08:26 UTC, miyagit commented on app/views/layouts/application.html.haml
> +    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
もうひとつハッシュロケットを直しましょう。

2019-04-30 08:39 UTC, yusuke39 commented
修正しました！
ご確認お願い致します。

2019-04-30 08:42 UTC, miyagit commented on app/assets/stylesheets/content.scss
> +    margin: 8px 0 0;
ここインデントずれてます！

2019-04-30 08:42 UTC, miyagit commented on app/assets/stylesheets/index.scss
> +i{
{の前にスペースを開けましょう。

2019-04-30 08:50 UTC, yusuke39 commented
何度も申し訳ありません。
スペース入れてみました！
ご確認お願い致します。

2019-04-30 08:55 UTC, ghost approved these changes
LGTMです！

2019-04-30 08:56 UTC, merged