ハンバーガーメニュー　マークアップ
itomaTech/freemarket_sample_49a pull request #52
Opened 2019-05-05 07:26 UTC by TTKeN

#WHAT
Index page のhamburger menu 
テーブルなしのためcss使用にて最低限の見た目で作成

#WHY
ユーザビリティ向上のため

2019-05-05 07:26 UTC, TTKeN commented
https://gyazo.com/c4456e40e8543c2ef2bc75f0839112c2

2019-05-05 07:31 UTC, TTKeN commented
[![Image from Gyazo](https://i.gyazo.com/c4456e40e8543c2ef2bc75f0839112c2.gif)](https://gyazo.com/c4456e40e8543c2ef2bc75f0839112c2)

2019-05-06 02:02 UTC, yuki-uchida requested changes

2019-05-06 02:02 UTC, yuki-uchida commented on app/views/shared/_header.html.haml
> +                    %a{:href => "3階層目のリンク"} カテゴリ2-3-1
link_toを使った方が可読性が高いので、link_toに統一しましょう

2019-05-06 02:30 UTC, TTKeN commented on app/views/shared/_header.html.haml
> +                    %a{:href => "3階層目のリンク"} カテゴリ2-3-1
link_toへ修正完了です。

2019-05-06 02:34 UTC, yuki-uchida commented
LGTMです！お疲れ様でした

2019-05-06 02:36 UTC, merged